<script lang="ts">
    import {loggedIn} from '$lib/localstores'    
	import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
	import { run } from 'svelte/internal';

    let bounty = "€ 50"
    let firstBounty = "€ 15 (COMPLETED)"
    let patch = "1.12 or higher."
    let category = "Midir%";
    let glitches = "Glitchless";
    let startingClass = "Thief";
    let weapon = "<a href=\"https://darksouls3.wiki.fextralife.com/Astora+Greatsword\" class=\"font-semibold hover:underline text-[#105D97]\" rel=\"nofollow\">Astora Greatsword</a>";
    let challenge = "<div class=\" italic text-lg font-medium mt-2\">Bosses allowed to be killed without the Astora Greatsword:</div><p>Iudex Gundyr<br/>Vordt of the Boreal Valley<br/>Crystal Sage</p><br/><div class=\" italic text-lg font-medium mt-2\">Extra restrictions</div><p>May not use any other weapon/item for damage after obtaining the Astora Greatsword.<br/>Must run to the Astora Greatsword and pick it up immediately after killing the Crystal Sage. (Grabbing the Cleansing Chapel bonfire first is allowed.)<br/>General <a href=\"https://www.speedrun.com/darksouls3?h=Any_Glitchless&x=jdz6v9v2\" class=\"font-semibold hover:underline text-[#105D97]\" rel=\"nofollow\">Any% Glitchless rules apply.</a><br/>Angel Skip Allowed.<br/>Fall Damage Cancel Allowed.<br/>Fence Skip Allowed.<br/>Greatwood Skip Allowed.<br/>Resin/Bundles Allowed<br/>Scream Skip Allowed.<br/>Wyvern Skip Allowed.<br/>Only non-damaging spells are allowed to be cast.<br/>Quitouts allowed.</p>";
    let deadline = "August 31st, 2023"
    let buttonEnabled = false;
    export let data;

    let runData: any[]=[];
    let runDataFiltered;


    onMount( ()=>{
        if($loggedIn == "true"){
        buttonEnabled = true;
        console.log(runData)
    }
    runData = data.verifiedRuns;
    })


function submitChallenge(){
    if ($loggedIn == "true"){
        goto(`/submit?Game=Dark%20Souls%203&Category=Midir%&Glitches%3F=Glitchless&Starting%20Class=Thief&Weapon%20(Only%20use%20this%20weapon)=Astora%20Greatsword&Challenge=Challenge%20of%20the%20Month%20July%20August`);
    }
    else{
        alert("You must be logged in.");
    }
}

</script>

<svelte:head>
    <title>SoulsBorneChallenges - Challenge of the Month</title> 
    <meta name="description" content="Every month, we'll have a Soulsborne bounty on a challenge for players to accomplish.">
</svelte:head>

<div class="justify-center items-center flex flex-col mx-auto mt-16">
    <h1 class="text-4xl font-extrabold md:text-7xl mt-4 mb-8 2xl:mt-12 px-4 lg:px-0">CHALLENGE OF THE MONTH</h1>
    <div id="maintext" class="px-4 lg:px-0 lg:w-2/3">
        <div class="">
            <p>Each month, a new bounty for a Soulsborne game will be placed here. This run is based off of a run generated by our <a href="/" class="font-bold hover:text-[#105D97]">challenge run generator</a>. These are meant to be fun little challenges, so please don't take it too seriously. </p>
        </div><br/>
        <div>
            <p>For the first month of this challenge, we'll be starting off with a simple one. The current challenge run for July / August 2023 is: </p>
        </div><br/>
            <div id="challengerun" class="flex flex-col mb-20 items-center">
                <h2 class="text-4xl font-extrabold ">Dark Souls 3 - Midora%</h2><br/>
                <div id="challengeInfo" class="flex flex-col lg:w-9/12 justify-between">
                <div class="inline-flex justify-between"><p class="font-semibold">Bounty (First to finish a run):</p><p>{firstBounty}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Bounty (fastest IGT):</p><p>{bounty}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Patch:</p><p>{patch}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Category:</p><p>{category}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Glitchless?:</p><p>{glitches}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Starting Class:</p><p>{startingClass}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Main Weapon:</p><p>{@html weapon}</p></div><br/>
                <div class="flex flex-col justify-between"><h2 class="font-bold text-2xl">Challenge</h2><p>{@html challenge}</p></div><br/>
                <div class="inline-flex justify-between"><p class="font-semibold">Submission Deadline:</p><p>{deadline}</p></div><br/>
                <div class="flex justify-end mt-2"><button on:click={() => submitChallenge()} class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-4 px-10 border border-blue-500 hover:border-transparent rounded">Submit a Run {#if buttonEnabled == false}<div class="inline-flex ">(must be logged in)</div>{/if}</button></div>
            </div>
        </div>
    </div>  


    <h2 class="font-bold text-2xl mt-16 mb-4">Verified Runs</h2>
    <div class="flex justify-center mb-32"><ul>
        {#if runData}
            {#each runData.reverse() as run, i}<li class="inline-flex mt-4 "><div class="flex justify-between border-2 rounded mx-2 px-2 lg:px-8 py-4 w-[95vw] lg:w-[40vw]"><div class="rank justify-start">{i+1}</div><div class="user flex flex-row"><div class="font-semibold">User:&nbsp;</div><div>{run.username}</div></div><div class="time flex flex-row"><div class="font-semibold">Time:</div><div>{run.timeHr}:{#if run.timeMins == 0}00{:else}{run.timeMins}{/if}:{run.timeSecs}</div></div><div><a href={run.video} target="_blank" rel="nofollow"><button>Watch Video</button></a></div></div></li><br/>{/each}
        {/if}
    </ul>
    </div>
</div>




<style>
    p{
        font-size: 1.125rem; /* 18px */
    line-height: 1.75rem; /* 28px */
    }

    a{
        font-weight: 700;
    }
    </style>