<script>
    import {loggedIn} from '$lib/localstores'    
	import { onMount } from 'svelte';

    let category = "Halflight%";
    let glitches = "Glitchless";
    let startingClass = "Sorcerer";
    let weapon = "<a href=//\"https://darksouls3.wiki.fextralife.com/Morne's+Great+Hammer\" class=\"font-semibold hover:underline text-[#105D97]\" rel=\"nofollow\">Morne's Great Hammer</a>";
    let challenge = "<div class=\" italic text-lg font-medium mt-2\">Bosses allowed to be killed without Morne's Great Hammer:</div><p>Iudex Gundyr<br/>Vordt of the Boreal Valley<br/>Dancer of the Boreal Valley</p><br/><div class=\" italic text-lg font-medium mt-2\">Extra restrictions</div><p>May not use any other weapon/item for damage after obtaining Morne's Great Hammer.<br/>Once in Undead Settlement, must rush to obtain Morne's Great Hammer before doing anything else.<br/>General <a href=\"https://www.speedrun.com/darksouls3?h=Any_Glitchless&x=jdz6v9v2\" class=\"font-semibold hover:underline text-[#105D97]\" rel=\"nofollow\">Any% Glitchless rules apply.</a><br/>Fall Damage Cancel Allowed.<br/>Fence Skip Allowed.<br/>Greatwood Skip Allowed.<br/>Wyvern Skip Allowed.<br/>Only non-damaging spells are allowed to be cast.<br/>Quitouts allowed.</p>";
    let deadline = "August 31st, 2023"
    let buttonEnabled = false;

    onMount( ()=>{
        if($loggedIn == "true"){
        buttonEnabled = true;
    }
    })


</script>

<div class="justify-center items-center flex flex-col mx-auto mt-16">
    <h1 class="text-4xl font-extrabold md:text-7xl mt-4 mb-8 2xl:mt-12 px-4 lg:px-0">CHALLENGE OF THE MONTH</h1>
    <div id="maintext" class="w-2/3">
        <div class="">
            <p>Each month, a new bounty for a Soulsborne game will be placed here. This run is based off of a run generated by our <a href="/" class="font-bold hover:text-[#105D97]">challenge run generator</a>. These are meant to be fun little challenges, so please don't take it too seriously. </p>
        </div><br/>
        <div>
            <p>For the first month of this challenge, we'll be starting off with a simple one. The current challenge run for July / August 2023 is: </p>
        </div><br/>
            <div id="challengerun" class="flex flex-col mb-20 items-center">
                <h2 class="text-4xl font-extrabold ">Dark Souls 3 - HalfHammer%</h2><br/>
                <div id="challengeInfo" class="flex flex-col w-9/12 justify-between">
                <div class="inline-flex justify-between"><p class="font-semibold">Category:</p><p>{category}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Glitchless?:</p><p>{glitches}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Starting Class:</p><p>{startingClass}</p></div>
                <div class="inline-flex justify-between"><p class="font-semibold">Main Weapon:</p><p>{@html weapon}</p></div><br/>
                <div class="flex flex-col justify-between"><h2 class="font-bold text-2xl">Challenge</h2><p>{@html challenge}</p></div><br/>
                <div class="inline-flex justify-between"><p class="font-semibold">Submission Deadline:</p><p>{deadline}</p></div><br/>
                <a href="/submit?Game=Dark%20Souls%203&Category=Halflight%&Glitches%3F=Glitchless&Starting%20Class=Sorcerer&Weapon%20(Only%20use%20this%20weapon)=Morne%27s%20Great%20Hammer&Challenge=Challenge%20of%20the%20Month%20July%20August"><button class="mr-6 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">Submit a Run {#if buttonEnabled == false}<div class="inline-flex ">(must be logged in)</div>{/if}</button></a>
            </div>
        </div>
    </div>  
</div>


<style>
    p{
        font-size: 1.125rem; /* 18px */
    line-height: 1.75rem; /* 28px */
    }

    a{
        font-weight: 700;
    }
    </style>